name: "Check sentiment"

on:
  issue_comment:
    types:
      - created

jobs:
  check-sentiment:
    runs-on: ubuntu-latest
    steps:
      - uses: jacobjmarks/quick-sentiment-analysis@v1
        id: sentiment-analysis
        with:
          text: ${{ github.event.comment.body }}
      - uses: actions/github-script@v6
        with:
          script: |
            const { comment } = context.payload;
            const result = '${{steps.sentiment-analysis.outputs.result}}';
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `Sentiment analysis results for [the comment](#issuecomment-${comment.id}) by @${comment.user.login} :`
                + `\n\n\`\`\` json\n${result}\n\`\`\``
            });
