name: "Check sentiment"

on:
  issue_comment:
    types:
      - created

jobs:
  check-sentiment:
    runs-on: ubuntu-latest
    steps:
      - uses: jacobjmarks/quick-sentiment-analysis@v1.0.0
        id: sentiment-analysis
        with:
          text: ${{ github.event.comment.body }}
      - uses: actions/github-script@v6
        with:
          script: |
            const { comment } = context.payload;
            const sentiment = '${{steps.sentiment-analysis.outputs.result}}';
            const quotedComment = comment.body.split('\n').map(l => `> ${l}`).join('\n');
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: quotedComment + '\n\n``` json\n${sentiment}\n```'
            })
